Universe 	= vanilla
Executable 	= run.sh
notification 	= Never
#Arguments       = $(infile)
Output  	= /sphenix/user/vbailey/logs/out/condor$(process).out
Error           = /sphenix/user/vbailey/logs/err/condor$(process).err
Log  		= /tmp/condor$(process)_vb.log
Initialdir  	= /sphenix/user/vbailey/ooanalysis
request_memory  = 1024MB
PeriodicHold    =  (NumJobStarts>=1 && JobStatus == 1 && !(ON_EVICT_CHECK_RequestMemory_REQUIREMENTS))
Queue 1